-- ----------------------------------------------------------------
-- 快递驿站智汇系统 · 一期结构快照（PostgreSQL）
-- 依据：docs/db.md 5.3（sql/schema 快照同步约定）
-- 内容：与 Flyway V1（db/migration/postgresql/V1__init_schema.sql）结构完全一致，
--       含全部注释；不含任何业务数据（种子数据见 Flyway V2）。
-- 用途：供评审与 DBA 查看；执行来源唯一为 Flyway 目录，
--       请勿直接以本快照为起点做增量变更。
-- 变更纪律：后续 Flyway 新增 Vn 结构脚本时，必须同步刷新本快照。
-- 库：kdyzgl（encoding UTF8，建库见 docs/deploy.md 与 TASK.md D02）
-- 与 MySQL 版的类型映射（db.md 1.5）：
--   主键 BIGINT GENERATED BY DEFAULT AS IDENTITY（允许显式插入种子 id）；
--   TINYINT→SMALLINT、INT→INTEGER、DATETIME→TIMESTAMP（无时区）、DATE→DATE；
--   列/表注释用 COMMENT ON，索引用独立 CREATE INDEX（索引名与 MySQL 版完全一致）。
-- 公共设计决策同 MySQL 版（db.md 第 1 章）：
--   D6 逻辑外键（不建物理 FOREIGN KEY）；D7 唯一性由 Service 层查重（仅普通索引）；
--   D8 时间字段应用层填充（仅 DEFAULT CURRENT_TIMESTAMP 兜底）；
--   login_log 为只插不改不删日志表，不设 is_deleted / update_time（db.md 3.4 例外约定）。
-- ----------------------------------------------------------------

CREATE TABLE department (
  id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id   BIGINT       NOT NULL DEFAULT 0,
  dept_name   VARCHAR(50)  NOT NULL,
  sort_order  INTEGER      NOT NULL DEFAULT 0,
  is_deleted  SMALLINT     NOT NULL DEFAULT 0,
  create_time TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE department IS '部门表（树形结构）';
COMMENT ON COLUMN department.id IS '主键';
COMMENT ON COLUMN department.parent_id IS '父部门ID，0=根节点';
COMMENT ON COLUMN department.dept_name IS '部门名称';
COMMENT ON COLUMN department.sort_order IS '同级排序（升序）';
COMMENT ON COLUMN department.is_deleted IS '逻辑删除：0=否，1=是';
COMMENT ON COLUMN department.create_time IS '创建时间';
COMMENT ON COLUMN department.update_time IS '更新时间（应用层维护）';

CREATE INDEX idx_department_parent_id ON department (parent_id);
CREATE INDEX idx_department_dept_name ON department (dept_name);

CREATE TABLE station (
  id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code           VARCHAR(50)  NOT NULL,
  station_name   VARCHAR(50)  NOT NULL,
  contact_person VARCHAR(50)  DEFAULT NULL,
  contact_phone  VARCHAR(20)  DEFAULT NULL,
  address        VARCHAR(255) DEFAULT NULL,
  status         SMALLINT     NOT NULL DEFAULT 1,
  remark         VARCHAR(255) DEFAULT NULL,
  is_deleted     SMALLINT     NOT NULL DEFAULT 0,
  create_time    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE station IS '驿站表';
COMMENT ON COLUMN station.id IS '主键';
COMMENT ON COLUMN station.code IS '驿站编码，活跃唯一，二期爬虫对接标识';
COMMENT ON COLUMN station.station_name IS '驿站名称';
COMMENT ON COLUMN station.contact_person IS '负责人姓名';
COMMENT ON COLUMN station.contact_phone IS '联系电话（出参脱敏）';
COMMENT ON COLUMN station.address IS '详细地址';
COMMENT ON COLUMN station.status IS '状态：0=停用，1=启用';
COMMENT ON COLUMN station.remark IS '备注';
COMMENT ON COLUMN station.is_deleted IS '逻辑删除：0=否，1=是';
COMMENT ON COLUMN station.create_time IS '创建时间';
COMMENT ON COLUMN station.update_time IS '更新时间（应用层维护）';

CREATE INDEX idx_station_code ON station (code);
CREATE INDEX idx_station_status ON station (status);

CREATE TABLE employee (
  id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username        VARCHAR(30)  NOT NULL,
  password        VARCHAR(100) NOT NULL,
  real_name       VARCHAR(50)  NOT NULL,
  phone           VARCHAR(20)  NOT NULL,
  gender          SMALLINT     NOT NULL DEFAULT 0,
  dept_id         BIGINT       DEFAULT NULL,
  station_id      BIGINT       DEFAULT NULL,
  role            VARCHAR(20)  NOT NULL DEFAULT 'STAFF',
  status          SMALLINT     NOT NULL DEFAULT 1,
  pwd_changed     SMALLINT     NOT NULL DEFAULT 0,
  entry_date      DATE         DEFAULT NULL,
  last_login_time TIMESTAMP    DEFAULT NULL,
  remark          VARCHAR(255) DEFAULT NULL,
  is_deleted      SMALLINT     NOT NULL DEFAULT 0,
  create_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE employee IS '员工表（员工即账号）';
COMMENT ON COLUMN employee.id IS '主键';
COMMENT ON COLUMN employee.username IS '登录账号，活跃唯一，创建后不可修改';
COMMENT ON COLUMN employee.password IS '密码散列（BCrypt $2a$ cost=10）';
COMMENT ON COLUMN employee.real_name IS '员工姓名';
COMMENT ON COLUMN employee.phone IS '手机号，活跃唯一，出参脱敏';
COMMENT ON COLUMN employee.gender IS '性别：0=未知，1=男，2=女';
COMMENT ON COLUMN employee.dept_id IS '所属部门ID（逻辑外键 department.id）';
COMMENT ON COLUMN employee.station_id IS '归属驿站ID（逻辑外键 station.id）';
COMMENT ON COLUMN employee.role IS '角色：ADMIN/STATION_ADMIN(二期)/STAFF';
COMMENT ON COLUMN employee.status IS '状态：0=禁用，1=启用';
COMMENT ON COLUMN employee.pwd_changed IS '密码是否已由本人修改：0=未修改，1=已修改';
COMMENT ON COLUMN employee.entry_date IS '入职日期';
COMMENT ON COLUMN employee.last_login_time IS '最后成功登录时间';
COMMENT ON COLUMN employee.remark IS '备注';
COMMENT ON COLUMN employee.is_deleted IS '逻辑删除：0=否，1=是';
COMMENT ON COLUMN employee.create_time IS '创建时间';
COMMENT ON COLUMN employee.update_time IS '更新时间（应用层维护）';

CREATE INDEX idx_employee_username    ON employee (username);
CREATE INDEX idx_employee_phone       ON employee (phone);
CREATE INDEX idx_employee_dept_id     ON employee (dept_id);
CREATE INDEX idx_employee_station_id  ON employee (station_id);
CREATE INDEX idx_employee_create_time ON employee (create_time);

CREATE TABLE login_log (
  id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username     VARCHAR(30)  NOT NULL,
  employee_id  BIGINT       DEFAULT NULL,
  login_ip     VARCHAR(50)  NOT NULL DEFAULT '',
  login_result SMALLINT     NOT NULL,
  fail_reason  VARCHAR(50)  DEFAULT NULL,
  user_agent   VARCHAR(255) DEFAULT NULL,
  login_time   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE login_log IS '登录日志表（只插不改不删）';
COMMENT ON COLUMN login_log.id IS '主键';
COMMENT ON COLUMN login_log.username IS '尝试登录的账号名';
COMMENT ON COLUMN login_log.employee_id IS '员工ID（账号存在时记录）';
COMMENT ON COLUMN login_log.login_ip IS '客户端IP（取 X-Forwarded-For 首个）';
COMMENT ON COLUMN login_log.login_result IS '登录结果：0=失败，1=成功';
COMMENT ON COLUMN login_log.fail_reason IS '失败原因（账号密码错误/账号已禁用）';
COMMENT ON COLUMN login_log.user_agent IS '浏览器UA（截断至255）';
COMMENT ON COLUMN login_log.login_time IS '登录时间';

CREATE INDEX idx_login_log_login_time  ON login_log (login_time);
CREATE INDEX idx_login_log_employee_id ON login_log (employee_id);
