-- ----------------------------------------------------------------
-- 快递驿站智汇系统 · 一期种子数据（PostgreSQL）
-- Flyway 迁移：V2__init_data.sql（对应任务 A04）
-- 权威设计：docs/db.md 5.2（V2 种子数据）
-- 说明：
--   1. 种子数据与 MySQL 版完全一致（部门「总公司」id=1 + 管理员 admin id=1）；
--   2. employee.password 为 BCrypt 散列（$2a$、cost=10、60 字符），与 MySQL 版
--      为同一字符串（同一密码、同一散列，已 compareSync 回环验证）；
--   3. pwd_changed=0：首次登录强制改密（requirement.md 决策 D1 双保险）；
--   4. create_time / update_time 由列默认值 CURRENT_TIMESTAMP 兜底填充；
--   5. GENERATED BY DEFAULT AS IDENTITY 允许显式插入种子 id（db.md 1.2 决策 D13），
--      但显式插入不会推进 IDENTITY 序列，末尾用 setval 重置序列，
--      保证后续自增插入从 2 开始（与 MySQL AUTO_INCREMENT 行为一致）。
-- ----------------------------------------------------------------

INSERT INTO department (id, parent_id, dept_name, sort_order)
VALUES (1, 0, '总公司', 1);

INSERT INTO employee (id, username, password, real_name, phone, gender, dept_id, station_id, role, status, pwd_changed)
VALUES (1, 'admin', '$2a$10$KzIKolEcoKaIeYkyJ7jr8e1GOMrz8wHaw9pppT6a42F5TU1dMGBSu', '系统管理员', '13800000000', 0, 1, NULL, 'ADMIN', 1, 0);

-- 显式插入 id=1 后 IDENTITY 序列仍停在初始位置，下一次自动生成会得到 id=1
-- 并与种子主键冲突；setval 将序列当前值置为 MAX(id)，下一次自增从 2 开始。
SELECT setval(pg_get_serial_sequence('department', 'id'), (SELECT MAX(id) FROM department));
SELECT setval(pg_get_serial_sequence('employee', 'id'), (SELECT MAX(id) FROM employee));
